version: "3.8"

services: 
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    networks:
      - splitwise_dev

  passfault:
    image: ccaamm/passfault
    hostname: splitwise_dev.passfault
    ports:
      - "9002:8080"
    networks:
      - splitwise_dev
  
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - splitwise_dev   

networks:
  splitwise_dev:
    external: true

volumes:
  mariadb_data: